# Django
export DJANGO_SECRET_KEY=''
export DJANGO_DEBUG=''
export DJANGO_USE_SENTRY=''

# Postgres
export DJANGO_POSTGRES_PASSWORD=''
export DJANGO_POSTGRES_HOST=''
export DJANGO_DATABASE_NAME=''
export DJANGO_MEDIA_FOLDER_NAME=''

# Elasticsearch
export DJANGO_ELASTICSEARCH_HOST=''

# AWS
export DJANGO_AWS_ACCESS_KEY_ID=''
export DJANGO_AWS_SECRET_ACCESS_KEY=''
export USE_S3=''
export DJANGO_AWS_S3_BUCKET_NAME=''
export DJANGO_AWS_S3_CUSTOM_DOMAIN=''

# Email
export DJANGO_EMAIL_HOST_USER=''
export DJANGO_EMAIL_HOST_PASSWORD=''

