# Django
export DJANGO_SECRET_KEY=''

# Postgres
export DJANGO_POSTGRES_PASSWORD=''
export DJANGO_POSTGRES_HOST=''
export DJANGO_DATABASE_NAME=''
export DJANGO_MEDIA_FOLDER_NAME=''

# Elasticsearch
export DJANGO_ELASTICSEARCH_HOST=''

# AWS
export DJANGO_AWS_ACCESS_KEY_ID=''
export DJANGO_AWS_SECRET_ACCESS_KEY=''
export USE_S3=''
export DJANGO_AWS_S3_BUCKET_NAME=''