"""
Django settings for photos project.

Generated by 'django-admin startproject' using Django 2.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

from django.contrib.messages import constants as messages

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ["DJANGO_SECRET_KEY"]

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ["DJANGO_DEBUG"] == "TRUE"

# Prod vars
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG
SECURE_REFERRER_POLICY = "same-origin"


ALLOWED_HOSTS = [
    "django-local",
    "django-local:8080",
    "localhost",
    "localhost:8000",
    "34.196.195.136",
    "lewdix.com",
    "www.lewdix.com",
]


# Application definition

INSTALLED_APPS = [
    "pages.apps.PagesConfig",
    "pictures.apps.PicturesConfig",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.postgres",
    "django.contrib.staticfiles",
    "storages",
    "sorl.thumbnail",
    "users",
    "debug_toolbar",
    "template_timings_panel",
]

MIDDLEWARE = [
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "photos.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "photos.wsgi.application"


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ["DJANGO_DATABASE_NAME"],
        "USER": "django",
        "PASSWORD": os.environ["DJANGO_POSTGRES_PASSWORD"],
        "HOST": os.environ["DJANGO_POSTGRES_HOST"],
    }
}

# Cache
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.memcached.MemcachedCache",
        "LOCATION": "127.0.0.1:11211",
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",},
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/
# https://testdriven.io/blog/storing-django-static-and-media-files-on-amazon-s3/

USE_S3 = os.environ["DJANGO_USE_S3"] == "TRUE"

if USE_S3:
    AWS_ACCESS_KEY_ID = os.environ["DJANGO_AWS_ACCESS_KEY_ID"]
    AWS_SECRET_ACCESS_KEY = os.environ["DJANGO_AWS_SECRET_ACCESS_KEY"]
    AWS_STORAGE_BUCKET_NAME = os.environ["DJANGO_AWS_S3_BUCKET_NAME"]
    AWS_DEFAULT_ACL = None
    AWS_S3_CUSTOM_DOMAIN = os.environ["DJANGO_AWS_S3_CUSTOM_DOMAIN"]
    AWS_S3_OBJECT_PARAMETERS = {"CacheControl": "max-age=86400"}

    # static settings
    STATIC_LOCATION = "static"
    STATIC_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/{STATIC_LOCATION}/"
    STATICFILES_STORAGE = "photos.storage_backends.StaticStorage"

    # public media settings
    PUBLIC_MEDIA_LOCATION = "media"
    MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/{PUBLIC_MEDIA_LOCATION}/"
    DEFAULT_FILE_STORAGE = "photos.storage_backends.PublicMediaStorage"
else:
    # Static Folder
    STATIC_ROOT = os.path.join(BASE_DIR, "static")
    STATIC_URL = "/static/"

    # Media Folder
    MEDIA_ROOT = os.path.join(BASE_DIR, os.environ["DJANGO_MEDIA_FOLDER_NAME"])
    MEDIA_URL = "/" + os.environ["DJANGO_MEDIA_FOLDER_NAME"] + "/"

STATICFILES_DIRS = [os.path.join(BASE_DIR, "photos/static")]


# How many characters a tag is allowed to be
MAX_TAG_LENGTH = 20
MIN_TAG_LENGTH = 1

# The characters allowed in a regex
VALID_TAG_REGEX = r"^[a-zA-Z0-9\-]*$"
INVALID_TAG_CHAR_REGEX = r"[^a-zA-Z0-9\-]"

# How many tags you are allowed to have
MAX_TAG_NUM = 5

# How many pictures to put on a page
PAGE_SIZE = 16
MAX_THEORETICAL_PAGE_SIZE_FOR_PLACEHOLDERS = 18

THUMBNAIL_SIZES = ["272"]

# Custom User / Authentication
AUTH_USER_MODEL = "users.CustomUser"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

# Message Tags
MESSAGE_TAGS = {
    messages.SUCCESS: "rounded bg-success text-black py-1 px-4 min-w-64 text-center mt-2 ml-2 z-10 text-lg message",
}

INTERNAL_IPS = [
    "127.0.0.1",
]

DEBUG_TOOLBAR_PANELS = [
    "debug_toolbar.panels.versions.VersionsPanel",
    "debug_toolbar.panels.timer.TimerPanel",
    "debug_toolbar.panels.settings.SettingsPanel",
    "debug_toolbar.panels.headers.HeadersPanel",
    "debug_toolbar.panels.request.RequestPanel",
    "debug_toolbar.panels.sql.SQLPanel",
    "debug_toolbar.panels.staticfiles.StaticFilesPanel",
    "debug_toolbar.panels.templates.TemplatesPanel",
    "debug_toolbar.panels.cache.CachePanel",
    "debug_toolbar.panels.signals.SignalsPanel",
    "debug_toolbar.panels.logging.LoggingPanel",
    "debug_toolbar.panels.redirects.RedirectsPanel",
    "debug_toolbar.panels.profiling.ProfilingPanel",
    "template_timings_panel.panels.TemplateTimings.TemplateTimings",
]

FORM_FIELD_CLASSES = [
    "focus:outline-none",
    "focus:border-input-selected",
    "appearance-none",
    "py-3",
    "my-3",
    "bg-surface-1",
    "opacity-high-emphasis",
    "rounded",
    "border-2",
    "border-default",
    "text-indent",
    "shadow-none",
    "border-color-transition",
    "disable-transition-on-theme-change",
]

FORM_FIELD_ERROR_CLASSES = ["border-error"]

# Email
# EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
# EMAIL_HOST = "localhost"
# EMAIL_USE_TLS = False
# EMAIL_PORT = 25
# EMAIL_HOST_USER = ""
# EMAIL_HOST_PASSWORD = ""
EMAIL_BACKEND = "django_amazon_ses.EmailBackend"
