# Generated by Django 3.0.2 on 2020-02-18 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='display_name',
            field=models.TextField(default='Unknown', max_length=30),
        ),
    ]
