# Generated by Django 3.0.2 on 2020-03-26 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_activated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='activated',
            new_name='email_confirmed',
        ),
    ]
