# Generated by Django 3.0.2 on 2020-04-06 18:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200326_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_email_dates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(blank=True), default=[], size=5),
        ),
    ]
