# Generated by Django 3.0.2 on 2020-04-14 23:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200406_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_upload_dates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(blank=True), default=list, size=50),
        ),
    ]
