Vagrant.configure("2") do |config|

    config.vm.define "web" do |web|
        web.vm.box = "hashicorp/bionic64"
        web.vm.network "private_network", ip: "10.0.0.2"
    end

    config.vm.define "db" do |db|
        db.vm.box = "hashicorp/bionic64"
        db.vm.network "private_network", ip: "10.0.0.3"
    end 
end
