Vagrant.configure("2") do |config|

    config.vm.define "web" do |web|
        web.vm.box = "hashicorp/bionic64"
        web.vm.network "private_network", ip: "10.0.0.2"
        web.vm.network "forwarded_port", guest: 80, host: 8080

	config.vm.synced_folder ".", "/vagrant", disabled: true

        web.vm.provision "ansible" do |ansible|
            ansible.playbook = "provisioning/web.yml"

            ansible.host_vars = {
                "web" => {"ansible_python_interpreter" => "/usr/bin/python3"}
            }
        end
    end

    config.vm.define "db" do |db|
        db.vm.box = "hashicorp/bionic64"
        db.vm.network "private_network", ip: "10.0.0.3"

	config.vm.synced_folder ".", "/vagrant", disabled: true

        
        db.vm.provision "ansible" do |ansible|
            ansible.playbook = "provisioning/db.yml"
        end
    end 
end
