# Generated by Django 3.0.2 on 2020-02-04 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='photo',
            field=models.ImageField(upload_to='pictures/%Y/%m/%d/'),
        ),
    ]
