# Generated by Django 2.2.6 on 2019-11-05 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0002_auto_20191105_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='picture',
            name='uploaded_at',
            field=models.DateTimeField(),
        ),
    ]
