# Generated by Django 3.0.2 on 2020-03-12 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0003_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='picture',
            name='tags2',
            field=models.ManyToManyField(to='pictures.Tag'),
        ),
    ]
