# Generated by Django 3.0.3 on 2020-03-14 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0004_auto_20200312_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='tags2',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='tags',
        ),
        migrations.AddField(
            model_name='picture',
            name='tags',
            field=models.ManyToManyField(to='pictures.Tag'),
        ),
    ]
