# Generated by Django 2.2.6 on 2019-11-06 21:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0004_auto_20191106_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, size=None),
        ),
    ]
