# Generated by Django 3.0.3 on 2020-03-15 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0005_auto_20200314_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
