# Generated by Django 2.2.6 on 2019-11-21 19:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0005_auto_20191106_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
