# Generated by Django 3.0.3 on 2020-03-16 01:56

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0007_auto_20200315_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='indexed_tags_search',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='picture',
            index=django.contrib.postgres.indexes.GinIndex(fields=['indexed_tags_search'], name='pictures_pi_indexed_b8ae4e_gin'),
        ),
    ]
