# Generated by Django 3.0.2 on 2020-03-19 22:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0010_picture_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='tags',
            field=models.TextField(blank=True, validators=[django.core.validators.RegexValidator('[a-zA-Z0-9- ]*', 'Tags must only contain characters lowercase a-z, numbers, and dashes (-)', code='invalid')]),
        ),
    ]
