# Generated by Django 3.0.2 on 2020-03-23 17:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0012_auto_20200319_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='thumbnail_w_272',
            field=models.ImageField(blank=True, upload_to='thumbnails/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='tags',
            field=models.TextField(blank=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9- ]*$', 'Tags must only contain characters lowercase a-z, numbers, and dashes (-)', code='invalid')]),
        ),
    ]
