# Generated by Django 3.0.2 on 2020-03-25 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0013_auto_20200323_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='thumbnail_w_272',
            field=models.ImageField(blank=True, upload_to='thumbnails/w272/%Y/%m/%d/'),
        ),
    ]
