# Generated by Django 3.0.2 on 2020-03-30 00:40

import django.core.validators
from django.db import migrations, models
import pictures.models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0014_auto_20200325_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='picture',
            name='tags',
            field=models.TextField(blank=True, validators=[django.core.validators.RegexValidator('^[a-z0-9- ]*$', 'Tags must only contain lowercase characters a-z, numbers, and dashes (-)', code='invalid'), pictures.models.validate_tags_under_max_length]),
        ),
    ]
