# Generated by Django 3.0.2 on 2020-03-30 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0015_auto_20200330_0040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='count',
        ),
        migrations.AddField(
            model_name='tag',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
