# Generated by Django 3.0.2 on 2020-03-30 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0016_auto_20200330_0044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='amount',
            new_name='count',
        ),
    ]
