# Generated by Django 3.0.2 on 2020-04-06 18:46

import django.core.validators
from django.db import migrations, models
import pictures.models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0017_auto_20200330_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='photo',
            field=models.ImageField(upload_to=pictures.models.get_photo_upload_path),
        ),
        migrations.AlterField(
            model_name='picture',
            name='tags',
            field=models.TextField(blank=True, validators=[django.core.validators.RegexValidator('^[a-z0-9- ]*$', 'Tags must only contain lowercase characters a-z, numbers, and dashes (-)', code='invalid'), pictures.models.validate_tags_under_max_length, pictures.models.validate_not_too_many_tags]),
        ),
    ]
