---
- hosts: all
  become: yes

  vars:
    python_version: 3.8

  tasks:
    - name: Set hostname
      hostname:
        name: web
  
    - name: add nginx repository
      apt_repository:
        repo: ppa:nginx/stable

    - name: Add deadsnakes repository
      apt_repository:
          repo: ppa:deadsnakes/ppa

    - name: Install packages
      apt:
        name: 
          - nginx
          - "python{{ python_version }}"
        state: latest
        update_cache: yes

    - name: Upgrade packages
      apt:
        upgrade: full
