---
- hosts: all
  become: yes

  vars:
    python_version: 3.8

  tasks:
    - name: Set hostname
      hostname:
        name: web
  
    - name: add nginx repository
      apt_repository:
        repo: ppa:nginx/stable

    - name: Add deadsnakes repository
      apt_repository:
          repo: ppa:deadsnakes/ppa

    - name: Install packages
      apt:
        name: 
          - nginx
          - python3-pip
          - python3.8
          - python3-distutils
          - python3.8-distutils
        state: latest
        update_cache: yes

    - name: Upgrade packages
      apt:
        upgrade: full

    - name: create django user
      user:
        name: django
        shell: /bin/bash
        comment: User for django to run as

    - name: create django ssh directory
      file:
        path: /home/django/.ssh
        state: directory
        owner: django
        group: django

    - name: Add github ssh key
      copy:
        src: ~/.ssh/ansible
        dest: /home/django/.ssh/id_rsa
        mode: '0600'
        owner: django
        group: django

    - name: Add ssh config
      copy:
        src: web_ssh_config
        dest: /home/django/.ssh/config
        owner: django
        group: django

    - name: Add known hosts file
      copy:
        src: web_known_hosts
        dest: /home/django/.ssh/known_hosts
        owner: django
        group: django

    - name: create checkouts directory
      file:
        path: /home/django/checkouts
        owner: django
        group: django
        state: directory
