---
- hosts: all
  become: yes
  tasks:
    - name: Set hostname
      hostname:
        name: web
  
    - name: add nginx repository
      apt_repository:
        repo: ppa:nginx/stable

    - name: Install nginx
      apt:
        name: nginx
        state: present
        update_cache: yes
 
    - name: Upgrade packages
      apt:
        upgrade: full
